<?php
/*
 * All Widgets
 */
include(get_template_directory().'/inc/widgets/price-widget.php');
include(get_template_directory().'/inc/widgets/categories-widget.php');
include(get_template_directory().'/inc/widgets/categories-widget-archive.php');
include(get_template_directory().'/inc/widgets/title-search-widget.php');
include(get_template_directory().'/inc/widgets/featured-ads-widget.php');
include(get_template_directory().'/inc/widgets/recent-ads-widget.php');
include(get_template_directory().'/inc/widgets/advertisement-widget.php');
include(get_template_directory().'/inc/widgets/search-custom-fields-widget.php');
include(get_template_directory().'/inc/widgets/simple-adsearch-widget.php');
include(get_template_directory().'/inc/widgets/assembly-widget.php');
include(get_template_directory().'/inc/widgets/ad-condition-widget.php');
include(get_template_directory().'/inc/widgets/ad-type-widget.php');
include(get_template_directory().'/inc/widgets/ad-warranty-widget.php');
include(get_template_directory().'/inc/widgets/ad-year-widget.php');
include(get_template_directory().'/inc/widgets/body-type-widget.php');
include(get_template_directory().'/inc/widgets/ad-transmission-widget.php');
include(get_template_directory().'/inc/widgets/engine-type-widget.php');
include(get_template_directory().'/inc/widgets/engine-capacity-widget.php');
include(get_template_directory().'/inc/widgets/color-family-widget.php');
include(get_template_directory().'/inc/widgets/ad-insurance-widget.php');
include(get_template_directory().'/inc/widgets/ad-milage-widget.php');
include(get_template_directory().'/inc/widgets/ad-location-widget.php');
include(get_template_directory().'/inc/widgets/ad-location-widget-archive.php');
include(get_template_directory().'/inc/widgets/location-radius-widget.php');